# Generated by Django 5.0.6 on 2024-05-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('number_r', models.IntegerField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('amount_r', models.FloatField(default=0)),
                ('average_price', models.FloatField(default=0)),
                ('average_price_r', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fines', models.FloatField(default=0)),
                ('surchages', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='returns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_id', models.IntegerField(default=None)),
                ('product_name', models.CharField(max_length=50)),
                ('refund_amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_price', models.FloatField(default=0)),
                ('comission', models.FloatField(default=0)),
                ('income', models.FloatField(default=0)),
                ('product_name', models.CharField(max_length=50)),
                ('nm_id', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storaging', models.FloatField(default=0)),
                ('recount_storaging', models.FloatField(default=0)),
                ('acceptanse', models.FloatField(default=0)),
            ],
        ),
    ]
