# Generated by Django 5.0.6 on 2024-05-31 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logistics',
            name='amount_r',
        ),
        migrations.RemoveField(
            model_name='logistics',
            name='average_price_r',
        ),
        migrations.RemoveField(
            model_name='logistics',
            name='number_r',
        ),
    ]
