# Generated by Django 5.0.6 on 2024-05-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_logistics_amount_r_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='other',
            name='compensation',
            field=models.FloatField(default=0),
        ),
    ]
