# Generated by Django 5.0.6 on 2024-05-12 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(default=None, max_length=40)),
                ('nmID', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('imtID', models.IntegerField(default=None)),
                ('vendorCode', models.CharField(default=None, max_length=40)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('price', models.CharField(default=None, max_length=60, null=True)),
                ('sizes', models.CharField(default=None, max_length=60, null=True)),
                ('brand', models.CharField(default=None, max_length=75)),
                ('category', models.CharField(default=None, max_length=100)),
                ('photo', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('nmID', models.IntegerField(default=None)),
                ('vendorCode', models.CharField(max_length=75)),
                ('sku', models.CharField(default=None, max_length=30, primary_key=True, serialize=False)),
                ('imtID', models.IntegerField(default=None)),
                ('size', models.CharField(max_length=50)),
                ('inWayToClient', models.IntegerField(default=0, null=True)),
                ('inWayFromClient', models.IntegerField(default=0, null=True)),
                ('quantityFull', models.IntegerField(default=0, null=True)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('editableSizePrice', models.BooleanField(default=False, null=True)),
                ('discountedPrice', models.FloatField(default=None, null=True)),
                ('discount', models.IntegerField(default=None, null=True)),
                ('price', models.IntegerField(default=None, null=True)),
                ('photo', models.CharField(default=None, max_length=255, null=True)),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouseName', models.CharField(default=None, max_length=100)),
                ('lastChangeDate', models.DateTimeField(default=None)),
                ('inWayToClient', models.IntegerField(default=None)),
                ('inWayFromClient', models.IntegerField(default=None)),
                ('quantityFull', models.IntegerField(default=None)),
                ('quantity', models.IntegerField(default=None)),
                ('sku', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.goods')),
            ],
        ),
    ]
