# Generated by Django 5.0.6 on 2024-05-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='nmID',
        ),
    ]
