# Generated by Django 5.0.6 on 2024-06-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productItemData', '0003_productdayorders_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdayorders',
            name='time',
            field=models.FloatField(default=None),
        ),
    ]
