# Generated by Django 5.0.6 on 2024-06-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productItemData', '0005_alter_productdayorders_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='productweekorders',
            name='time',
            field=models.IntegerField(default=None),
        ),
    ]
