# Generated by Django 5.0.6 on 2024-06-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productItemData', '0006_productweekorders_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='productweekorders',
            name='size',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
